services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn home.wsgi:application
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        value: 'your-django-secret-key-here'
