# Generated by Django 5.2.3 on 2025-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalHome', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
